FROM eclipse-temurin:17-jdk
WORKDIR /app
EXPOSE 8089

# Copier le jar généré par Maven
COPY target/student-management-0.0.1-SNAPSHOT.jar student-management.jar

ENTRYPOINT ["java","-jar","student-management.jar"]
